export default function AIPanel({ recommendation }) {
  if (!recommendation) return null;

  if (recommendation.error) {
    return (
      <div className="ai-panel">
        <div className="ai-head">
          <div className="ai-icon">✦</div>
          <h3>AI recommendation unavailable</h3>
        </div>
        <div className="ai-summary">{recommendation.error}</div>
      </div>
    );
  }

  return (
    <div className="ai-panel">
      <div className="ai-head">
        <div className="ai-icon">✦</div>
        <h3>Generated by SolarShield AI</h3>
        <span>{recommendation._self_check === "passed" ? "Self-checked" : "Unverified"}</span>
      </div>

      <div className="ai-summary">{recommendation.summary}</div>

      {recommendation.per_site_notes?.length > 0 && (
        <div className="ai-notes">
          {recommendation.per_site_notes.map((n, i) => (
            <div className="ai-note" key={i}>
              <span className="bullet">▸</span>
              <span>
                <b>{n.name}</b> — {n.note}
              </span>
            </div>
          ))}
        </div>
      )}

      {recommendation.risk_flags?.map((flag, i) => (
        <div className="risk-flag" key={i}>
          ⚠ {flag}
        </div>
      ))}
    </div>
  );
}
